service: express-lambda
frameworkVersion: '>=1.0.0 <2.0.0'
configValidationMode: error
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2
  deploymentBucket:
    name: qa-jenkins-release
  role: arn:aws:iam::651958565740:role/lambda-qa
functions:
 server:
   description: Test and example of an Express Lambda application with a public API
   handler: src/index.server
   events:
     - http:
         path: test
         method: get
         cors: true